
import hashlib
import logging

from random import choice
from string import ascii_lowercase

logger = logging.getLogger("hashing")
logging.basicConfig(level=logging.DEBUG)


class PasswordHashing:

    # SALT_LENGTH = 5

    def __init__(self):
        pass

    def pass_check(self) -> str:
        """
            Asks the user to enter the password twice. Repeats the operation
            as long as input strings are not identical.

            :return (str) password: password given by the user for hashing functions.
        """
        input_pass = input("Please enter the password.")
        input_pass2 = input("Please repeat the password.")
        while input_pass != input_pass2:
            logger.info("Passwords are incorrect.")
            input_pass = input("Please enter the password again.")
            input_pass2 = input("Please repeat the password.")
        return input_pass

    def generate_salt(self, SALT_LENGTH = 5) -> str:
        """
            Generates string to concat it with the password and create a hash.
        :param (int) SALT_LENGTH: length of the generated salt.

        :return (str) salt: salt generated for the user's password.
        """

        salt = "".join(choice(ascii_lowercase) for i in range(SALT_LENGTH))
        return salt

    def old_hash(self, password: str, salt: str) -> str:
        """
            Generates salted password's hash using SHA256 hashing algorithm,
            then stores it in SQLite database.
        :param (str) password: password given by an user.
        :param (str) salt: salt generated by an auxiliary function.

        :return (str) hash: salted password's hash.
        :return (str) salt: password's salt in plain text.
        """
        pass_to_hash = password + salt
        h = hashlib.sha256()
        h.update(pass_to_hash.encode())
        # zapisac w bazie hash hasla czyli h.hexdigest()
        # zapisac w bazie sol jako plain text

        return logger.info(f"Password's hash: {h.hexdigest()} and salt {salt} saved in the database")

    def new_hash(self, password: str, salt: str) -> str:
        """
            Generates salted password's hash using HMAC generator,
            then stores it in SQLite database.
        :param (str) password: password given by an user.
        :param (str) salt: salt generated by an auxiliary function.

        :return (str) hash: salted password's hash.
        :return (str) salt: password's salt in plain text.
        """
        out = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 100000).hex()
        # zapisac w bazie hash hasla czyli h.hexdigest()
        # zapisac w bazie sol jako plain text

        return logger.info(f"Password's hash: {out} and salt {salt} saved in the database")


if __name__ == "__main__":

    ps = PasswordHashing()
    password = ps.pass_check()
    logger.info(f"Saved password: {password}")
    salt = ps.generate_salt()
    logger.info(f"Saved salt: {salt}")



