
import hashlib
import logging

import sqlite3
from sqlite3 import Error

from random import choice
from string import ascii_letters

logger = logging.getLogger("hashing")
logging.basicConfig(level=logging.DEBUG)


def create_connection(db_file):
    """
        Creates a database connection to a SQLite database
    :param (str) db_file: path to db file in CWD.

    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)

    return conn


def create_table(conn, create_table_sql):
    """
        Creates a table from the create_table_sql statement
    :param conn: Connection object
    :param create_table_sql: a CREATE TABLE statement
    """
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)


class PasswordHashing:

    SALT_LENGTH = 5

    def __init__(self):
        pass

    def pass_check(self) -> str:
        """
            Asks the user to enter the password twice. Repeats the operation
            as long as input strings are not identical.

            :return (str) password: password given by the user for hashing functions.
        """
        input_pass = input("Please enter the password. Password must be at least 6 characters long.")
        input_pass2 = input("Please repeat the password.")
        while input_pass != input_pass2 and len(input_pass) < 6:
            input_pass2 = ""  # So it would not match with only one new input_pass
            logger.info("Passwords are incorrect.")
            input_pass = input("Please enter the password again. Password must be at least 6 characters long.")
            input_pass2 = input("Please repeat the password.")
        return input_pass

    def generate_salt(self, SALT_LENGTH) -> str:
        """
            Generates string to concat it with the password and create a hash.
        :param (int) SALT_LENGTH: length of the generated salt.

        :return (str) salt: salt generated for the user's password.
        """

        salt = "".join(choice(ascii_letters) for i in range(SALT_LENGTH))
        return salt

    def old_hash(self, conn, password: str, salt: str) -> str:
        """
            Generates salted password's hash using SHA256 hashing algorithm,
            then stores it in SQLite database.
        :param (str) conn: Connection object.
        :param (str) password: password given by an user.
        :param (str) salt: salt generated by an auxiliary function.

        :return (str) hash: salted password's hash.
        :return (str) salt: password's salt in plain text.
        """
        pass_to_hash = password + salt
        h = hashlib.sha256()
        h.update(pass_to_hash.encode())
        out = h.hexdigest()

        sql = '''INSERT INTO passwords(p_hash, p_salt)
        VALUES(out, salt); '''

        cur = conn.cursor()
        cur.execute(sql)
        conn.commit()

        return logger.info(f"Password's hash: {h.hexdigest()} and salt {salt} saved in the database")

    def new_hash(self, conn, password: str, salt: str) -> str:
        """
            Generates salted password's hash using HMAC generator,
            then stores it in SQLite database.
        :param (str) conn: Connection object.
        :param (str) password: password given by an user.
        :param (str) salt: salt generated by an auxiliary function.

        :return (str) hash: salted password's hash.
        :return (str) salt: password's salt in plain text.
        """
        out = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 100000).hex()

        sql = '''INSERT INTO passwords(p_hash, p_salt)
        VALUES(out, salt); '''

        cur = conn.cursor()
        cur.execute(sql)
        conn.commit()

        return logger.info(f"Password's hash: {out} and salt {salt} saved in the database")


    def verify_password(self, conn, input_id, input_pass):
        """
            Verifies password given id and input password.
            Hashes input_pass and compares it to the
            user's password's hash stored in the database.
        :param (str) conn: Connection object.
        :param (int) input_id: id of the user for which the passwords are compared.
        :param (str) input_pass: string given by the user.

        :return (str) confirmation if the password is correct.
        """
        sql = '''SELECT p_hash FROM passwords
                WHERE p_id = input_id; '''

        cur = conn.cursor()
        db_hash = cur.execute(sql)

        sql2 = '''SELECT p_salt FROM passwords
                        WHERE p_id = input_id; '''

        cur2 = conn.cursor()
        db_salt = cur2.execute(sql2)

        #  Hashes input password salted with proper salt. Compares to adequate hash given password id.
        input_hash = hashlib.pbkdf2_hmac("sha256", input_pass.encode(), db_salt.encode(), 100000).hex()
        if input_hash == db_hash:
            return logger.info("Password is correct")
        else:
            return logger.info("Password is invalid")


def main():
    database = r"\sqlite\db\passwords.db"  # Project's directory is set as Sources Root
    sql_create_passwords_table = """ CREATE TABLE IF NOT EXISTS passwords (
                                               p_id integer PRIMARY KEY AUTOINCREMENT,
                                               p_hash text NOT NULL,
                                               p_salt text NOT NULL
                                           ); """
    conn = create_connection(database)
    if conn is not None:
        create_table(conn, sql_create_passwords_table)

    ps = PasswordHashing()
    password = ps.pass_check()
    logger.info(f"Saved password: {password}")
    salt = ps.generate_salt()
    logger.info(f"Saved salt: {salt}")

    ps.verify_password(conn, 1, "123456")


if __name__ == "__main__":
    main()





